
server:
    port: 5050



spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/test-db
    username: haruka
    password: pass
  jpa:
    database: POSTGRESQL

logging:
  level:
    root: INFO